src/Entity/Centre.php
<?php

namespace App\Entity;

use App\Repository\CentreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CentreRepository::class)
 */
class Centre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_centre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $description_centre;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_centre;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $photo_centre;

    /**
     * @ORM\OneToMany(targetEntity=Activite::class, mappedBy="Centre", orphanRemoval=true)
     */
    private $activites;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Centre", orphanRemoval=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->activites = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNomCentre(): ?string
    {
        return $this->nom_centre;
    }

    public function setNomCentre(string $nom_centre): self
    {
        $this->nom_centre = $nom_centre;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(string $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDescriptionCentre(): ?string
    {
        return $this->description_centre;
    }

    public function setDescriptionCentre(string $description_centre): self
    {
        $this->description_centre = $description_centre;

        return $this;
    }

    public function getPrixCentre(): ?float
    {
        return $this->prix_centre;
    }

    public function setPrixCentre(float $prix_centre): self
    {
        $this->prix_centre = $prix_centre;

        return $this;
    }

    public function getPhotoCentre()
    {
        return $this->photo_centre;
    }

    public function setPhotoCentre($photo_centre): self
    {
        $this->photo_centre = $photo_centre;

        return $this;
    }

    /**
     * @return Collection|Activite[]
     */
    public function getActivites(): Collection
    {
        return $this->activites;
    }

    public function addActivite(Activite $activite): self
    {
        if (!$this->activites->contains($activite)) {
            $this->activites[] = $activite;
            $activite->setCentre($this);
        }

        return $this;
    }

    public function removeActivite(Activite $activite): self
    {
        if ($this->activites->removeElement($activite)) {
            // set the owning side to null (unless already changed)
            if ($activite->getCentre() === $this) {
                $activite->setCentre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setCentre($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCentre() === $this) {
                $reservation->setCentre(null);
            }
        }

        return $this;
    }
}

src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement extends AbstractController
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="float")
     */
    private $prix_event;

    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $descrption_event;

    /**
     * @ORM\Column(type="blob")
     */
    private $photo_event;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Evenement")
     */
    private $reservations;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id_event;
    }

    public function getPrix(): ?float
    {
        return $this->prix_event;
    }

    public function setPrix(float $prix_event): self
    {
        $this->prix = $prix_event;

        return $this;
    }

    public function getDescrptionEvent(): ?string
    {
        return $this->descrption_event;
    }

    public function setDescrptionEvent(string $descrption_event): self
    {
        $this->descrption_event = $descrption_event;

        return $this;
    }

    public function getPhotoEvent()
    {
        return $this->photo_event;
    }

    public function setPhotoEvent($photo_event): self
    {
        $this->photo_event = $photo_event;

        return $this;
    }
    public function affiche(){
        $repo=$this->getDoctrine()->getRepository(evenement::class);
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setEvenement($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getEvenement() === $this) {
                $reservation->setEvenement(null);
            }
        }

        return $this;
    }
}

src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Client;

    /**
     * @ORM\ManyToOne(targetEntity=Centre::class, inversedBy="reservations")
     */
    private $Centre;

    /**
     * @ORM\ManyToOne(targetEntity=Evenement::class, inversedBy="reservations")
     */
    private $Evenement;

    /**
     * @ORM\ManyToOne(targetEntity=Materiels::class, inversedBy="reservations")
     */
    private $Materiels;




    public function getIdReservation(): ?int
    {
        return $this->id_reservation;
    }

    public function getClient(): ?Client
    {
        return $this->Client;
    }

    public function setClient(?Client $Client): self
    {
        $this->Client = $Client;

        return $this;
    }

    public function getCentre(): ?Centre
    {
        return $this->Centre;
    }

    public function setCentre(?Centre $Centre): self
    {
        $this->Centre = $Centre;

        return $this;
    }

    public function getEvenement(): ?Evenement
    {
        return $this->Evenement;
    }

    public function setEvenement(?Evenement $Evenement): self
    {
        $this->Evenement = $Evenement;

        return $this;
    }

    public function getMateriels(): ?Materiels
    {
        return $this->Materiels;
    }

    public function setMateriels(?Materiels $Materiels): self
    {
        $this->Materiels = $Materiels;

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=CentreComment::class, mappedBy="user")
     */
    private $centreComments;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Client")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Centre::class, mappedBy="User")
     */
    private $centres;

    public function __construct()
    {
        $this->centreComments = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->centres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|CentreComment[]
     */
    public function getCentreComments(): Collection
    {
        return $this->centreComments;
    }

    public function addCentreComment(CentreComment $centreComment): self
    {
        if (!$this->centreComments->contains($centreComment)) {
            $this->centreComments[] = $centreComment;
            $centreComment->setUser($this);
        }

        return $this;
    }

    public function removeCentreComment(CentreComment $centreComment): self
    {
        if ($this->centreComments->removeElement($centreComment)) {
            // set the owning side to null (unless already changed)
            if ($centreComment->getUser() === $this) {
                $centreComment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setClient($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getClient() === $this) {
                $reservation->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Centre[]
     */
    public function getCentres(): Collection
    {
        return $this->centres;
    }

    public function addCentre(Centre $centre): self
    {
        if (!$this->centres->contains($centre)) {
            $this->centres[] = $centre;
            $centre->setUser($this);
        }

        return $this;
    }

    public function removeCentre(Centre $centre): self
    {
        if ($this->centres->removeElement($centre)) {
            // set the owning side to null (unless already changed)
            if ($centre->getUser() === $this) {
                $centre->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/index", name="default")
     */
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }
    
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     * @Route("/", name="reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }
}

templates/default/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn waves-effect waves-light btn-danger">Delete</button>
</form>

templates/default/reservation/_form.html.twig
<form class="l-f" method="post"  enctype="multipart/form-data">

{{ form_start(form) }}
    {{ form_widget(form) }}



<button type="submit" class="btn">save</button>


{{ form_end(form) }}

templates/default/reservation/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
<h1>Modifier une reservation</h1>

<div class="card">
    <div class="card-body">

        {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

        <a href="{{ path('reservation_index') }}">back to list</a>

        {{ include('reservation/_delete_form.html.twig') }}
        {% endblock %}

templates/default/reservation/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <h1>Liste des reservations</h1>
    <div class="card">
        <div class="card-body">

            <table class="dash__table-2">
                <thead>
                <tr>
                    <th>Client</th>
                    <th>Centre</th>
                    <th>Evenement</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>
                {% for reservation in reservations %}
                    {% if (reservation.client.Username == app.User.Username) %}
                    <tr>
                        <td>{{ reservation.client.Username }}</td>
                        <td>{{ reservation.Centre.nomCentre }}</td>
                        <td>{{ reservation.Evenement.descrptionEvent }}</td>
                        <td><img src="{{ reservation.qrCode }}" style="width: 100px;height: 100px"></td>

                        <td>
                            <form method="post" action="{{ path('reservation_deleteF', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
                                <button class="btn waves-effect waves-light btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                    {% endif %}
                {% else %}
                    <tr>
                        <td colspan="2">non reservation trouvez</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            <a href="{{ path('reservation_newF') }}" type="button" class="btn btn-info "><i
                        class="fa fa-plus-circle"></i> Aouter une reservation</a>



            <a href="{{ path('genPdf') }}" type="button" class="btn btn-success"><i
                        class="fa fa-check"></i>  Telecharger Pdf </a>
            </table>
        </div>
    </div>
    </div>

    <div class="row">
        <!-- Column -->
        <div class="col-lg-8 col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex m-b-40 align-items-center no-block">
                        <h5 class="card-title ">SALES DIFFERENCE</h5>
                        <div class="ml-auto">
                            <ul class="list-inline font-12">
                                <li><i class="fa fa-circle text-cyan"></i> SITE A</li>
                                <li><i class="fa fa-circle text-primary"></i> SITE B</li>
                            </ul>
                        </div>
                    </div>
                    <div id="morris-area-chart2" style="height: 340px;"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-4 col-md-12">
        <div class="row">
            <!-- Column -->
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">SALES DIFFERENCE</h5>
                        <div class="row">
                            <div class="col-6  m-t-30">
                                <h1 class="text-info">$647</h1>
                                <p class="text-muted">APRIL 2017</p>
                                <b>(150 Sales)</b> </div>
                            <div class="col-6">
                                <div id="sparkline2dash" class="text-right"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}


{% block custom_script %}

    <script src="../assets/node_modules/raphael/raphael-min.js"></script>
    <script src="../assets/node_modules/morrisjs/morris.min.js"></script>
    <script src="../assets/node_modules/jquery-sparkline/jquery.sparkline.min.js"></script>
    <script>

    </script>





{% endblock %}

templates/default/reservation/new.html.twig
{% extends 'base.html.twig' %}


{% block body %}
<h1>Passer une reservation</h1>
<div class="card">
    <div class="card-body">

        {{ include('reservation/_form.html.twig') }}

        <a href="{{ path('reservation_index') }}">Liste des reservations</a>

    </div>
</div>


{% endblock %}

templates/default/reservation/show.html.twig
{% extends 'layout.html.twig' %}


{% block body %}
    <h1>Détails du reservation de :{{ reservation.client.username }}</h1>
    <div class="card">
        <div class="card-body">

            <table class="table">
                <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ reservation.id }}</td>
                </tr>
                <tr>
                    <td>Client</td>
                    <td>
                        {{ reservation.client.Username }}
                    </td>
                </tr>
                <tr>
                    <td>Client</td>
                    <td>
                        {{ reservation.client.Username }}
                    </td>
                </tr>
                <tr>
                    <td>Centre</td>
                    <td>
                        {{ reservation.centre.nomCentre }}
                    </td>
                </tr>
                <tr>
                    <td>Centre</td>
                    <td>
                        {{ reservation.evenement.descrptionEvent }}
                    </td>
                </tr>
                <tr>
                    <td>QrCode</td>
                    <td>
                        <img style="width:100px; height:100px;" src="{{ reservation.Qrcode }}"/>
                    </td>
                </tr>

                </tbody>
            </table>

            <a href="{{ path('reservation_index') }}">retour </a>

            <a href="{{ path('reservation_edit', {'id': reservation.id}) }}">Modifier</a>

            {{ include('reservation/_delete_form.html.twig') }}

            </table>
        </div>
    </div>

{% endblock %}

templates/default/reservation/tab.html.twig
<!DOCTYPE html>
<html>
<head>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            text-align: center;
            padding: 8px;
        }
        mid {
            text-align: center;
            padding: 15px;

        }

        tr:nth-child(even){background-color: #f2f2f2}

        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>
<body>
<h1> Liste des reservation</h1>
<table class="table product-overview" id="myTable">
    <thead>
    <tr>
        <th>Id</th>
        <th>Client</th>
        <th>Centre</th>
        <th>Evenement</th>
    </tr>
    </thead>
    <tbody>
    {% for reservation in reservations %}
        <tr>
            <td>{{ reservation.id }}</td>
            <td>{{ reservation.Client.nom }}</td>
            <td>{{ reservation.Centre.nomCentre }}</td>
            <td>{{ reservation.Evenement.descrptionEvent }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="5">Pas de reservation !</td>
        </tr>
    {% endfor %}

    </tbody>
</table>


</body>
</html>