src/Entity/Centre.php
<?php

namespace App\Entity;

use App\Repository\CentreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CentreRepository::class)
 */
class Centre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_centre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $description_centre;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_centre;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $photo_centre;

    /**
     * @ORM\OneToMany(targetEntity=Activite::class, mappedBy="Centre", orphanRemoval=true)
     */
    private $activites;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Centre", orphanRemoval=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->activites = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNomCentre(): ?string
    {
        return $this->nom_centre;
    }

    public function setNomCentre(string $nom_centre): self
    {
        $this->nom_centre = $nom_centre;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(string $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDescriptionCentre(): ?string
    {
        return $this->description_centre;
    }

    public function setDescriptionCentre(string $description_centre): self
    {
        $this->description_centre = $description_centre;

        return $this;
    }

    public function getPrixCentre(): ?float
    {
        return $this->prix_centre;
    }

    public function setPrixCentre(float $prix_centre): self
    {
        $this->prix_centre = $prix_centre;

        return $this;
    }

    public function getPhotoCentre()
    {
        return $this->photo_centre;
    }

    public function setPhotoCentre($photo_centre): self
    {
        $this->photo_centre = $photo_centre;

        return $this;
    }

    /**
     * @return Collection|Activite[]
     */
    public function getActivites(): Collection
    {
        return $this->activites;
    }

    public function addActivite(Activite $activite): self
    {
        if (!$this->activites->contains($activite)) {
            $this->activites[] = $activite;
            $activite->setCentre($this);
        }

        return $this;
    }

    public function removeActivite(Activite $activite): self
    {
        if ($this->activites->removeElement($activite)) {
            // set the owning side to null (unless already changed)
            if ($activite->getCentre() === $this) {
                $activite->setCentre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setCentre($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCentre() === $this) {
                $reservation->setCentre(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=CentreComment::class, mappedBy="user")
     */
    private $centreComments;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Client")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Centre::class, mappedBy="User")
     */
    private $centres;

    public function __construct()
    {
        $this->centreComments = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->centres = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|CentreComment[]
     */
    public function getCentreComments(): Collection
    {
        return $this->centreComments;
    }

    public function addCentreComment(CentreComment $centreComment): self
    {
        if (!$this->centreComments->contains($centreComment)) {
            $this->centreComments[] = $centreComment;
            $centreComment->setUser($this);
        }

        return $this;
    }

    public function removeCentreComment(CentreComment $centreComment): self
    {
        if ($this->centreComments->removeElement($centreComment)) {
            // set the owning side to null (unless already changed)
            if ($centreComment->getUser() === $this) {
                $centreComment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setClient($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getClient() === $this) {
                $reservation->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Centre[]
     */
    public function getCentres(): Collection
    {
        return $this->centres;
    }

    public function addCentre(Centre $centre): self
    {
        if (!$this->centres->contains($centre)) {
            $this->centres[] = $centre;
            $centre->setUser($this);
        }

        return $this;
    }

    public function removeCentre(Centre $centre): self
    {
        if ($this->centres->removeElement($centre)) {
            // set the owning side to null (unless already changed)
            if ($centre->getUser() === $this) {
                $centre->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/CentreType.php
<?php

namespace App\Form;

use App\Entity\Centre;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CentreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
{
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Centre::class,
        ]);
    }
}

src/Controller/CentreController.php
<?php

namespace App\Controller;

use App\Entity\Centre;
use App\Form\Centre1Type;
use App\Repository\CentreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/centre")
 */
class CentreController extends AbstractController
{
    /**
     * @Route("/", name="centre_index", methods={"GET"})
     */
    public function index(CentreRepository $centreRepository): Response
    {
        return $this->render('centre/index.html.twig', [
            'centres' => $centreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="centre_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $centre = new Centre();
        $form = $this->createForm(Centre1Type::class, $centre);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {

            


           
            $centre->setNomCentre($request->get('nom_centre'));
            $centre->setOwner($request->get('owner'));
            $centre->setAdresse($request->get('address'));
            $centre->setDescriptionCentre($request->get('description_centre'));
            $centre->setPrixCentre($request->get('prix_centre'));
            $fich = $request->files->get('photo_centre');
            $new_name = rand() . '.' . $fich->getClientOriginalExtension();
            $fich->move('uploads/', $new_name);
        
            $centre->setPhotoCentre($new_name);
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($centre);
            $entityManager->flush();

            return $this->redirectToRoute('centre_index');
        }

        return $this->render('centre/new.html.twig', [
            'centre' => $centre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="centre_show", methods={"GET"})
     */
    public function show(Centre $centre): Response
    {
        return $this->render('centre/show.html.twig', [
            'centre' => $centre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="centre_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Centre $centre): Response
    {   
        $form = $this->createForm(Centre1Type::class, $centre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $centre->setNomCentre($request->get('nom_centre'));
            $centre->setOwner($request->get('owner'));
            $centre->setAdresse($request->get('address'));
            $centre->setDescriptionCentre($request->get('description_centre'));
            $centre->setPrixCentre($request->get('prix_centre'));
            $fich = $request->files->get('photo_centre');
            $new_name = rand() . '.' . $fich->getClientOriginalExtension();
            $fich->move('uploads/', $new_name);
        
            $centre->setPhotoCentre($new_name);
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($centre);
            $entityManager->flush();
            

            return $this->redirectToRoute('centre_index');
        }

        return $this->render('centre/edit.html.twig', [
            'centre' => $centre,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="centre_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Centre $centre): Response
    {
        if ($this->isCsrfTokenValid('delete'.$centre->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($centre);
            $entityManager->flush();
        }

        return $this->redirectToRoute('centre_index');
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/index", name="default")
     */
    public function index(): Response
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }
    
}

templates/default/centre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Centre{% endblock %}

{% block body %}


            <!--====== Tab 1 ======-->
            <div class="tab-pane" id="e-l-p">
                <div class="slider-fouc">
                    <div class="owl-carousel tab-slider" data-item="4">
                        {% for centre in centres %}
                            <div class="u-s-m-b-30">
                                <div class="product-o product-o--hover-on">
                                    <div class="product-o__wrap">

                                        <a class="aspect aspect--bg-grey aspect--square u-d-block"
                                           href="product-detail.html">

                                            <img class="aspect__img" src="{{ asset('uploads/')~centre.PhotoCentre }}"
                                                 alt=""></a>
                                        <div class="product-o__action-wrap">
                                        </div>
                                    </div>

                                    <span class="product-o__name">

                                                            <a href="{{ path('centre_afficher', { 'id':  centre.id }) }}">{{ centre.nomCentre }}</a></span>
                                    <div class="product-o__rating gl-rating-style"><i class="far fa-star"></i><i
                                                class="far fa-star"></i><i
                                                class="far fa-star"></i><i class="far fa-star"></i><i
                                                class="far fa-star"></i>

                                        <span class="product-o__review">(0)</span></div>

                                    <span class="product-o__price">{{ centre.owner }}

                                                            <span class="product-o__price">{{ centre.prixCentre }}</span></span>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>


{% endblock %}

templates/default/centre/mescentre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Centre{% endblock %}

{% block body %}


            <!--====== Tab 1 ======-->
            <div class="tab-pane" id="e-l-p">
                <div class="slider-fouc">
                    <div class="owl-carousel tab-slider" data-item="4">
                        {% for centre in centres %}
                            {% if (centre.user.Username == app.user.Username) %}
                            <div class="u-s-m-b-30">
                                <div class="product-o product-o--hover-on">
                                    <div class="product-o__wrap">

                                        <a class="aspect aspect--bg-grey aspect--square u-d-block"
                                           href="product-detail.html">

                                            <img class="aspect__img" src="{{ asset('uploads/')~centre.PhotoCentre }}"
                                                 alt=""></a>
                                        <div class="product-o__action-wrap">
                                        </div>
                                    </div>

                                    <span class="product-o__name">

                                                            <a href="{{ path('centre_afficher', { 'id':  centre.id }) }}">{{ centre.nomCentre }}</a></span>
                                    <div class="product-o__rating gl-rating-style"><i class="far fa-star"></i><i
                                                class="far fa-star"></i><i
                                                class="far fa-star"></i><i class="far fa-star"></i><i
                                                class="far fa-star"></i>

                                        <span class="product-o__review">(0)</span></div>

                                    <span class="product-o__price">{{ centre.owner }}

                                                            <span class="product-o__price">{{ centre.prixCentre }}</span></span>
                                    <span class="product-o__price">
                                        <form method="post" action="{{ path('centre_del', {'id': centre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ centre.id) }}">

                                            <button type="submit" class="btn"><i class="fa fa-trash"></i></button>
</form>

                                    </span>


                                </div>


                            </div>

                        {% endif %}

                        {% endfor %}

                    </div>
                </div>
            </div>


{% endblock %}

templates/default/centre/show.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <h1>Détails de centre:{{ centre.nomCentre }}</h1>


    <div class="row">
        <!-- Column -->
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    =
                    <div class="row">
                        <div class="col-lg-5 col-md-5 col-sm-5">
                            <div class="white-box text-center" ><img src="{{ asset('uploads/')~centre.photoCentre }}"
                              style="width:500px;height:500px;" class="img-responsive"></div>
                        </div>
                        <div class="col-lg-7 col-md-7 col-sm-7">
                            <h4 class="box-title m-t-40">centre description</h4>
                            <p>{{ centre.descriptionCentre }}</p>
                            <h2 class="m-t-40">{{ centre.prixCentre }}<small class="text-success"> DT</small></h2>
                            <div class="col-md-7 col-sm-7">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <h3 class="box-title m-t-40">Informations Générales</h3>
                                    <div class="table-responsive">
                                        <table class="table">
                                            <tbody>
                                            <tr>
                                                <th>Nom centre</th>
                                                <td>{{ centre.nomCentre }}</td>
                                            </tr>
                                            <tr>
                                                <th>Rating</th>
                                                <td>
                                                    <div class="pc-meta">
                                                        <div class="rating" id="#rat">
                                                            {% if is_granted('ROLE_USER') %}

                                                                {% for i in 1.. rat %}
                                                                    <i class="fa fa-star" width="20px"
                                                                       data-index="{{ i }}"
                                                                       onclick="rating({{ i }}, {{ centre.id }})"></i>
                                                                {% endfor %}
                                                                {% if  rat  < 5 %}
                                                                    {% for i in rat..4 %}
                                                                        <i class="fa fa-star" aria-hidden="true"
                                                                           style="color: white" data-index="{{ i }}"
                                                                           onclick="rating({{ i+1 }},{{ centre.id }})"
                                                                           width="20px"></i>
                                                                    {% endfor %}
                                                                {% endif %}
                                                            {% else %}
                                                                {% for i in 1..rat %}
                                                                    <i class="fa fa-star" width="20px"></i>
                                                                {% endfor %}
                                                                {% if rat < 5 %}
                                                                    {% for i in rat..4 %}
                                                                        <i class="fa fa-star" width="20px"></i>
                                                                    {% endfor %}
                                                                {% endif %}
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                    <script>

                                                        var rateIndex = -1;
                                                        $(document).ready(function(){
                                                            $('.fa-star').on('click', function(){
                                                                rateIndex = parseInt($(this).data('index'));
                                                            });
                                                            $('.fa-star').mouseover(function(){
                                                                resetStarColors();
                                                                var currentIndex = parseInt($(this).data('index'));
                                                                for (var i=0; i <= currentIndex; i++)
                                                                {
                                                                    $('.fa-star:eq('+i+')').css('color', 'yellow');
                                                                }

                                                            });
                                                            $('.fa-star').mouseleave(function(){
                                                                if(rateIndex = -1)
                                                                {
                                                                    for (var i=0; i <= currentIndex; i++)
                                                                    {
                                                                        $('.fa-star:eq('+i+')').css('color', 'yellow');
                                                                    }
                                                                }

                                                            });
                                                        });
                                                        function resetStarColors(){
                                                            $('.fa-star').css('color', 'white');
                                                        }

                                                    </script>

                                                </td>
                                            </tr>
                                            <tr>
                                                <th>Owner</th>
                                                <td>{{ centre.owner }}</td>
                                            </tr>
                                            <tr>
                                                <th>Adresse</th>
                                                <td>{{ centre.adresse }}</td>
                                            </tr>

                                            <tr>
                                                <th>Activité</th>
                                                    {% for centre in centre.activites %}
                                                    <td>
                                                        {{ centre.DescreptionActivite }}
                                                    </td>

                                            {% else %}

                                            {% endfor %}
                                            </tr>

                                            <tr>
                                                <td>commentaires</td>
                                            </tr>
                                            {% for centre in centre.centreComments %}
                                                <tr>
                                                    <td>
                                                        {{ centre.user.username }} :
                                                        {{ centre.contenu }}
                                                    </td>
                                                </tr>
                                            {% else %}

                                            {% endfor %}

                                            <tr>
                                                <td>
                                                    Commentaire : <input type="text" name="contenu" id="contenu">
                                                    <input type="hidden" value="{{ centre.id }}" name="id">
                                                    <button id="btn" onclick="myF({{ centre.id }})">
                                                        Commenter
                                                    </button>
                                                    <script>
                                                        function myF(id) {
                                                            $.get("http://localhost:8000/admin/centre/newComment?id=" + id + "&contenu=" + document.getElementById("contenu").value, function (data) {
                                                                location.reload();
                                                            });

                                                        }
                                                    </script>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                        <div>
                                            <a href="{{ path('reservation_newF') }}">Reserver Centre</a>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Column -->
            </div>
        </div>
    </div>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script type="text/javascript">
        function rating(pos, id) {
            $.ajax({
                type: "GET",
                url: "{{ path('centre_rating') }}",
                data: {
                    'rat': pos,
                    'id': id
                },
                success: function () {
                    alert("done");

                }
            });

        }

    </script>

{% endblock %}