src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PromotionRepository::class)
 */
class Promotion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name= "id_promo" , type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_promo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $desc_promo;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $image_promo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_promo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prix_ancien;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prix_nv;

    /**
     * @return mixed
     */
    public function getPrixAncien()
    {
        return $this->prix_ancien;
    }

    /**
     * @param mixed $prix_ancien
     */
    public function setPrixAncien($prix_ancien): void
    {
        $this->prix_ancien = $prix_ancien;
    }

    /**
     * @return mixed
     */
    public function getPrixNv()
    {
        return $this->prix_nv;
    }

    /**
     * @param mixed $prix_nv
     */
    public function setPrixNv($prix_nv): void
    {
        $this->prix_nv = $prix_nv;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }




    public function getTitrePromo(): ?string
    {
        return $this->titre_promo;
    }

    public function setTitrePromo(string $titre_promo): self
    {
        $this->titre_promo = $titre_promo;

        return $this;
    }

    public function getDescPromo(): ?string
    {
        return $this->desc_promo;
    }

    public function setDescPromo(string $desc_promo): self
    {
        $this->desc_promo = $desc_promo;

        return $this;
    }

    public function getImagePromo()
    {
        return $this->image_promo;
    }

    public function setImagePromo($image_promo): self
    {
        $this->image_promo = $image_promo;

        return $this;
    }

    public function getTypePromo(): ?string
    {
        return $this->type_promo;
    }

    public function setTypePromo(string $type_promo): self
    {
        $this->type_promo = $type_promo;

        return $this;
    }
}

src/Entity/Publicite.php
<?php

namespace App\Entity;

use App\Repository\PubliciteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PubliciteRepository::class)
 */
class Publicite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_pub;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description_pub;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $image_pub;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitrePub(): ?string
    {
        return $this->titre_pub;
    }

    public function setTitrePub(string $titre_pub): self
    {
        $this->titre_pub = $titre_pub;

        return $this;
    }

    public function getDescriptionPub(): ?string
    {
        return $this->description_pub;
    }

    public function setDescriptionPub(string $description_pub): self
    {
        $this->description_pub = $description_pub;

        return $this;
    }

    public function getImagePub()
    {
        return $this->image_pub;
    }

    public function setImagePub($image_pub): self
    {
        $this->image_pub = $image_pub;

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use App\Repository\PubliciteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/promotion")
 */
class PromotionController extends AbstractController
{
    /**
     * @Route("/front/index", name="promotion_front_index", methods={"GET"})
     */
    public function frontIndex(PromotionRepository $promotionRepository, PubliciteRepository $publiciteRepository): Response
    {
        return $this->render('promotion/front_index.html.twig', [
            'publicites' => $publiciteRepository->findAll(),
            'promotions' => $promotionRepository->findAll(),
            'countTypes'=>$promotionRepository->countPromotionByTypes()

        ]);
    }
    /**
     * @Route("/front/index/orderNewPrice", name="promotion_front_index_order_New", methods={"GET"})
     */
    public function orderNewIndex(PromotionRepository $promotionRepository, PubliciteRepository $publiciteRepository): Response
    {
        return $this->render('promotion/front_index.html.twig', [
            'publicites' => $publiciteRepository->findAll(),
            'promotions' => $promotionRepository->orderByPriceNew(),
            'countTypes'=>$promotionRepository->countPromotionByTypes()

        ]);
    }
    /**
     * @Route("/front/index/orderOldPrice", name="promotion_front_index_order_Old", methods={"GET"})
     */
    public function orderOldIndex(PromotionRepository $promotionRepository, PubliciteRepository $publiciteRepository): Response
    {
        return $this->render('promotion/front_index.html.twig', [
            'publicites' => $publiciteRepository->findAll(),
            'promotions' => $promotionRepository->orderByPriceOld(),
            'countTypes'=>$promotionRepository->countPromotionByTypes()

        ]);
    }
    /**
     * @Route("/", name="promotion_index", methods={"GET"})
     */
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
            'countTypes'=>$promotionRepository->countPromotionByTypes()

        ]);
    }

    /**
     * @Route("/new", name="promotion_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotion->setTitrePromo($request->get('titre_promo'));
            $promotion->setDescPromo($request->get('description_promo'));
            $promotion->setTypePromo($request->get('type_promo'));
            $promotion->setPrixAncien($request->get('prix_ancien'));
            $promotion->setPrixNv($request->get('prix_nv'));
            $fich = $request->files->get('image_promo');
            $new_name = rand() . '.' . $fich->getClientOriginalExtension();
            $fich->move('uploads/', $new_name);

            $promotion->setImagePromo($new_name);
            $entityManager = $this->getDoctrine()->getManager();

            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_show", methods={"GET"})
     */
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="promotion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Promotion $promotion): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotion->setTitrePromo($request->get('titre_promo'));
            $promotion->setDescPromo($request->get('desc_promo'));
            $promotion->setTypePromo($request->get('type_promo'));
            $promotion->setPrixAncien($request->get('prix_ancien'));
            $promotion->setPrixNv($request->get('prix_nv'));
            $fich = $request->files->get('image_promo');
            $new_name = rand() . '.' . $fich->getClientOriginalExtension();
            $fich->move('uploads/', $new_name);
            $promotion->setImagePromo($new_name);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('promotion_index');
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="promotion_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Promotion $promotion): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('promotion_index');
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Nouvelle Promotion{% endblock %}

{% block body %}
    <h1>Modifier Promotion</h1>

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="{{ path('promotion_index') }}">Promotion</a></li>
                <li class="breadcrumb-item active"><a href="{{ path('promotion_new') }}">Modifier</a></li>
            </ol>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">

                <a href="{{ path('promotion_new') }}"  type="button" class="btn btn-info "><i class="fa fa-plus-circle"></i> Ajouter</a>
            </div>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Modifiez Votre Promotion</h4>
                    <form method="post"  enctype="multipart/form-data">
                        {{ form_start(form) }}

                        <div class="form-group ">
                            <label for="adr"  class="control-label">Titre de la promotion</label>
                            <input class="form-control" type="text" name="titre_promo"  value="{{promotion.titrePromo}}" minlength="4" maxlength="50" required>
                        </div>
                        <div class="form-group ">
                            <label for="desc"  class="control-label">Description de la promotion</label>
                            <textarea class="form-control"   rows="4" name="desc_promo" minlength="4" maxlength="300" required >{{promotion.descPromo}}</textarea>
                        </div>
                        <div class="form-group ">
                            <label for="desc"  class="control-label">Type de la promotion</label>
                            <textarea class="form-control"   rows="4" name="type_promo" minlength="4" maxlength="300" required >{{promotion.typePromo}}</textarea>
                        </div>
                        <div class="form-group ">
                            <label for="adr"  class="control-label">prix Ancien</label>
                            <input class="form-control" type="text" name="prix_ancien" minlength="4" maxlength="50" required>
                        </div>
                        <div class="form-group ">
                            <label for="adr"  class="control-label">Prix Nv</label>
                            <input class="form-control" type="text" name="prix_nv" minlength="4" maxlength="50" required>
                        </div>

                        <div class="form-group ">

                            <label for="ph" class="control-label">Image de la promotion</label>
                            <input type="file" id="ph" class="dropify" data-show-remove="false" data-default-file="{{ asset('uploads/')~promotion.imagePromo }}" name="image_promo" accept="image/x-png,image/gif,image/jpeg" />

                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i>Modifier</button>
                            <a type="button" class="btn btn-secondary" href="{{ path('promotion_index') }}">Annuler</a>
                        </div>
                        {{ form_end (form) }}
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">

            <ol class="breadcrumb">

                <a href="{{ path('promotion_index') }}">Retour à la liste</a>

            </ol>
        </div>
    </div>

{% endblock %}

templates/promotion/front_index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block slider %}
    <!--====== Primary Slider ======-->
    <div class="s-skeleton s-skeleton--h-600 s-skeleton--bg-grey">
        <div class="owl-carousel primary-style-1" id="hero-slider">
            {% for publicite in publicites %}
                <div class="hero-slide hero-slide--1">
                    <img class="aspect__img" src="{{ asset('uploads/') ~ publicite.imagePub}}" alt="{{ publicite.imagePub}}" width="1920" height="900">
                    <div class="container">

                             <div class="row">
                                <div class="col-12">
                                <div class="slider-content slider-content--animation">

                                    <span class="content-span-1 u-c-secondary">{{ publicite.titrePub }}</span>
                                    <span class="content-span-3 u-c-secondary">{{ publicite.descriptionPub }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!--====== End - Primary Slider ======-->
{% endblock %}
{% block body %}
    <div class="filter-category-container">
        <div class="filter__category-wrapper">

            <a class="btn filter__btn filter__btn--style-1 js-checked" type="button" href="{{ path('promotion_front_index') }}">Tous</a></div>
        <div class="filter__category-wrapper">

            <a class="btn filter__btn filter__btn--style-1" type="button" href="{{ path('promotion_front_index_order_Old') }}">Tri par ANCIEN PRIX</a></div>
        <div class="filter__category-wrapper">

            <a class="btn filter__btn filter__btn--style-1" type="button" href="{{ path('promotion_front_index_order_New') }}">Tri par NOUVEAU PRIX</a></div>

    </div>
    <div class="filter__grid-wrapper u-s-m-t-30">


        <div class="row">
            {% for promotion in promotions %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 u-s-m-b-30 filter__item headphone">
                <div class="product-o product-o--hover-on product-o--radius">
                    <div class="product-o__wrap">

                        <a class="aspect aspect--bg-grey aspect--square u-d-block" href="product-detail.html">

                            <img class="aspect__img" src="{{ asset('uploads/') ~ promotion.imagePromo }}" alt="{{ promotion.titrePromo }}"></a>
                        <div class="product-o__action-wrap">
                            <ul class="product-o__action-list">
                                <li>

                                    <a data-modal="modal" data-modal-id="#quick-look" data-tooltip="tooltip" data-placement="top" title="Quick View"><i class="fas fa-search-plus"></i></a></li>
                                <li>

                                    <a data-modal="modal" data-modal-id="#add-to-cart" data-tooltip="tooltip" data-placement="top" title="Add to Cart"><i class="fas fa-plus-circle"></i></a></li>
                                <li>

                                    <a href="signin.html" data-tooltip="tooltip" data-placement="top" title="Add to Wishlist"><i class="fas fa-heart"></i></a></li>
                                <li>

                                    <a href="signin.html" data-tooltip="tooltip" data-placement="top" title="Email me When the price drops"><i class="fas fa-envelope"></i></a></li>
                            </ul>
                        </div>
                    </div>

                    <span class="product-o__category"> <a href="shop-side-version-2.html">{{ promotion.typePromo }}</a></span>

                    <span class="product-o__name">  <a href="product-detail.html">{{ promotion.titrePromo }}</a></span>
                    <div class="product-o__rating gl-rating-style"><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i>

                        <span class="product-o__review">(23)</span>
                    </div>
                    <span class="product-o__category">   <a href="shop-side-version-2.html">{{ promotion.descPromo }}</a></span>
                    <span class="product-o__price">{{ promotion.prixNv }}<span class="product-o__discount">{{ promotion.prixAncien }}</span></span>
                </div>
            </div>
            {% endfor %}
            <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 u-s-m-b-30 filter__item smartphone">
                <div class="product-o product-o--hover-on product-o--radius">
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}




{% block custom_script %}

    <script>
        $(function () {
            var data = [
                {% for row in countTypes %}
                {
                label: "{{ row.type }}",
                 data: "{{ row.nombre }}"
                 },

                {% endfor %}

            ];
            var plotObj = $.plot($("#flot-pie-chart"), data, {
                series: {
                    pie: {
                        innerRadius: 0.5
                        , show: true
                    }
                }
                , grid: {
                    hoverable: true
                }
                , color: null
                , tooltip: true
                , tooltipOpts: {
                    content: "%p.0%, %s Promo" , // show percentages, rounding to 2 decimal places
                    shifts: {
                        x: 20
                        , y: 0
                    }
                    , defaultTheme: false
                }
            });
        });


    </script>





{% endblock %}

templates/promotion/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Promotion </h1>

    <div class="row page-titles">
        <div class="d-flex justify-content-end align-items-centper">

            <a href="{{ path('promotion_new') }}" type="button" class="btn btn-info "><i
                        class="fa fa-plus-circle"></i>  Ajouter </a>
        </div>
    </div>

    <div class="row">

        <!-- Column -->
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table product-overview" id="myTable">
                            <thead>
                            <tr>
                                <th>Id</th>
                                <th>Titre_promo</th>
                                <th>Description_promo</th>
                                <th>Type_promo</th>
                                <th>Prix An</th>
                                <th>Prix Nv</th>
                                <th>Image_promo</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for promotion in promotions %}
                                <tr>
                                    <td>{{ promotion.id }}</td>
                                    <td>{{ promotion.titrePromo }}</td>
                                    <td>{{ promotion.descPromo }}</td>
                                    <td>{{ promotion.typePromo }}</td>
                                    <td>{{ promotion.prixAncien }}</td>
                                    <td>{{ promotion.prixNv }}</td>
                                    <td><img src="{{ asset('uploads/')~promotion.imagePromo}}" alt="imgpromo" width="96" height="96"></td>
                                    <td><a href="{{ path('promotion_show', { 'id':  promotion.id }) }}"
                                           title="Afficher" data-toggle="tooltip"><i class="ti-eye"></i></a>
                                        <a href="{{ path('promotion_edit', { 'id':  promotion.id }) }}"
                                           title="Modifier"  data-toggle="tooltip"  ><i class="ti-marker-alt"></i></a>
                                        <a href="{{ path('promotion_delete', { 'id':  promotion.id }) }}"
                                           title="Supprimer" data-toggle="tooltip"  ><i class="fa fa-close text-danger"></i></a>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="5">Pas de promotion !</td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Stat</h4>
                    <div class="flot-chart">
                        <div class="flot-chart-content" id="flot-pie-chart"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Column -->
    </div>

{% endblock %}




{% block custom_script %}

    <script>
        $(function () {
            var data = [
                {% for row in countTypes %}
                {
                label: "{{ row.type }}",
                 data: "{{ row.nombre }}"
                 },

                {% endfor %}

            ];
            var plotObj = $.plot($("#flot-pie-chart"), data, {
                series: {
                    pie: {
                        innerRadius: 0.5
                        , show: true
                    }
                }
                , grid: {
                    hoverable: true
                }
                , color: null
                , tooltip: true
                , tooltipOpts: {
                    content: "%p.0%, %s Promo" , // show percentages, rounding to 2 decimal places
                    shifts: {
                        x: 20
                        , y: 0
                    }
                    , defaultTheme: false
                }
            });
        });


    </script>





{% endblock %}

templates/promotion/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Nouvelle Promotion{% endblock %}

{% block body %}
    <h1>Créer une Promotion</h1>

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <ol class="breadcrumb">

                <li class="breadcrumb-item active"><a href="{{ path('promotion_index') }}">Promotion</a></li>
                <li class="breadcrumb-item active"><a href="{{ path('promotion_new') }}">Ajouter</a></li>
            </ol>
        </div>

    </div>
    <div class="row">

        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Ajoutez Votre Promotion</h4>
                    <form method="post"  enctype="multipart/form-data">
                        {{ form_start(form) }}


                        <div class="form-group ">
                            <label for="adr"  class="control-label">Titre de la promotion</label>
                            <input class="form-control" type="text" name="titre_promo" minlength="4" maxlength="50" required>
                        </div>
                        <div class="form-group ">
                            <label for="desc"  class="control-label">Description de la promotion</label>
                            <textarea class="form-control"   rows="4" name="description_promo" minlength="4" maxlength="300" required ></textarea>
                        </div>

                        <div class="form-group ">
                            <label for="desc"  class="control-label">Type de la promotion :</label>

                            <textarea class="form-control"   rows="4" name="type_promo" minlength="4" maxlength="300" required ></textarea>
                        </div>
                        <div class="form-group ">
                            <label for="adr"  class="control-label">prix Ancien</label>
                            <input class="form-control" type="text" name="prix_ancien" minlength="4" maxlength="50" required>
                        </div>
                        <div class="form-group ">
                            <label for="adr"  class="control-label">Prix Nv</label>
                            <input class="form-control" type="text" name="prix_nv" minlength="4" maxlength="50" required>
                        </div>

                        <div class="form-group ">

                            <label for="ph" class="control-label">Image de la promotion</label>
                            <input type="file" id="ph" class="dropify" data-show-remove="false" name="image_promo" accept="image/x-png,image/gif,image/jpeg" required/>

                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn btn-success"> <i class="fa fa-check"></i>Ajouter</button>
                            <a type="button" class="btn btn-secondary" href="{{ path('promotion_index') }}">Annuler</a>
                        </div>
                        {{ form_end (form) }}
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <ol class="breadcrumb">

                <button class="breadcrumb-item active"><a href="{{ path('promotion_index') }}">Retour à la liste</a></button>

            </ol>
        </div>
    </div>




{% endblock %}

templates/promotion/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="{{ path('promotion_index') }}">Promotion</a></li>
            </ol>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">

                <a href="{{ path('promotion_new') }}" type="button" class="btn btn-info "><i
                            class="fa fa-plus-circle"></i> Ajouter </a>

            </div>
        </div>
    </div>

    <div class="row">
        <!-- Column -->
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    =                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-6">
                            <div class="white-box text-center"><img src="{{ asset('uploads/') ~ promotion.imagePromo }}"
                                                                    class="img-responsive"></div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <h3 class="box-title m-t-40">Informations Promotion </h3>
                            <div class="table-responsive">
                                <table class="table">
                                    <tbody>
                                    <tr>
                                        <th>Id</th>
                                        <td>{{ promotion.id }}</td>
                                    </tr>
                                    <tr>
                                        <th>Titre promotion </th>
                                        <td>{{ promotion.titrePromo }}</td>
                                    </tr>
                                    <tr>
                                        <th>Description promotion </th>
                                        <td>{{ promotion.descPromo }}</td>
                                    </tr>
                                    <tr>
                                    <th>Type promotion </th>
                                    <td>{{ promotion.typePromo }}</td>
                                    </tr>
                                    <tr>
                                    <th>Image promotion </th>
                                    <td>{{ promotion.imagePromo }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                                {{ include('promotion/_delete_form.html.twig') }}
                                <a href="{{ path('promotion_edit', {'id': promotion.id}) }}" class="btn btn-alert">Modifier</a>
                                <div>
                                    <a href="{{ path('promotion_index') }}">Retour à la liste </a>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Column -->
    </div>

{% endblock %}