src/Entity/Activite.php
<?php

namespace App\Entity;

use App\Repository\ActiviteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ActiviteRepository::class)
 */
class Activite
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id_activite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DescreptionActivite;

    /**
     * @ORM\Column(type="float")
     */
    private $PrixActivite;

    /**
     * @ORM\ManyToOne(targetEntity=Centre::class, inversedBy="activites")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Centre;


    public function getIdActivite() : ?int
    {
        return $this->id_activite;
    }



    public function getDescreptionActivite(): ?string
    {
        return $this->DescreptionActivite;
    }

    public function setDescreptionActivite(string $DescreptionActivite): self
    {
        $this->DescreptionActivite = $DescreptionActivite;

        return $this;
    }

    public function getPrixActivite(): ?float
    {
        return $this->PrixActivite;
    }

    public function setPrixActivite(float $PrixActivite): self
    {
        $this->PrixActivite = $PrixActivite;

        return $this;
    }

    public function getCentre(): ?Centre
    {
        return $this->Centre;
    }

    public function setCentre(?Centre $Centre): self
    {
        $this->Centre = $Centre;

        return $this;
    }
}

src/Entity/Centre.php
<?php

namespace App\Entity;

use App\Repository\CentreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CentreRepository::class)
 */
class Centre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_centre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=2000)
     */
    private $description_centre;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_centre;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $photo_centre;

    /**
     * @ORM\OneToMany(targetEntity=Activite::class, mappedBy="Centre", orphanRemoval=true)
     */
    private $activites;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="Centre", orphanRemoval=true)
     */
    private $reservations;

    public function __construct()
    {
        $this->activites = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNomCentre(): ?string
    {
        return $this->nom_centre;
    }

    public function setNomCentre(string $nom_centre): self
    {
        $this->nom_centre = $nom_centre;

        return $this;
    }

    public function getOwner(): ?string
    {
        return $this->owner;
    }

    public function setOwner(string $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDescriptionCentre(): ?string
    {
        return $this->description_centre;
    }

    public function setDescriptionCentre(string $description_centre): self
    {
        $this->description_centre = $description_centre;

        return $this;
    }

    public function getPrixCentre(): ?float
    {
        return $this->prix_centre;
    }

    public function setPrixCentre(float $prix_centre): self
    {
        $this->prix_centre = $prix_centre;

        return $this;
    }

    public function getPhotoCentre()
    {
        return $this->photo_centre;
    }

    public function setPhotoCentre($photo_centre): self
    {
        $this->photo_centre = $photo_centre;

        return $this;
    }

    /**
     * @return Collection|Activite[]
     */
    public function getActivites(): Collection
    {
        return $this->activites;
    }

    public function addActivite(Activite $activite): self
    {
        if (!$this->activites->contains($activite)) {
            $this->activites[] = $activite;
            $activite->setCentre($this);
        }

        return $this;
    }

    public function removeActivite(Activite $activite): self
    {
        if ($this->activites->removeElement($activite)) {
            // set the owning side to null (unless already changed)
            if ($activite->getCentre() === $this) {
                $activite->setCentre(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setCentre($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getCentre() === $this) {
                $reservation->setCentre(null);
            }
        }

        return $this;
    }
}

src/Form/ActiviteType.php
<?php

namespace App\Form;

use App\Entity\Activite;
use App\Entity\Centre;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ActiviteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('DescreptionActivite')
            ->add('PrixActivite')
            ->add('Centre', EntityType::class, [
                // looks for choices from this entity
                'class' => Centre::class,

                // uses the User.username property as the visible option string
                'choice_label' => 'nom_centre',

                // used to render a select box, check boxes or radios
                // 'multiple' => true,
                // 'expanded' => true,
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Activite::class,
        ]);
    }
}

src/Controller/ActiviteController.php
<?php

namespace App\Controller;

use App\Entity\Activite;
use App\Form\ActiviteType;
use App\Repository\ActiviteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/activite")
 */
class ActiviteController extends AbstractController
{
    /**
     * @Route("/", name="activite_index", methods={"GET"})
     */
    public function index(ActiviteRepository $activiteRepository): Response
    {
        return $this->render('activite/index.html.twig', [
            'activites' => $activiteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="activite_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $activite = new Activite();
        $form = $this->createForm(ActiviteType::class, $activite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($activite);
            $entityManager->flush();

            return $this->redirectToRoute('activite_index');
        }

        return $this->render('activite/new.html.twig', [
            'activite' => $activite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_activite}", name="activite_show", methods={"GET"})
     */
    public function show(Activite $activite): Response
    {
        return $this->render('activite/show.html.twig', [
            'activite' => $activite,
        ]);
    }

    /**
     * @Route("/{id_activite}/edit", name="activite_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Activite $activite): Response
    {
        $form = $this->createForm(ActiviteType::class, $activite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('activite_index');
        }

        return $this->render('activite/edit.html.twig', [
            'activite' => $activite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_activite}", name="activite_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Activite $activite): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activite->getId_activite(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($activite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('activite_index');
    }
}

templates/activite/_delete_form.html.twig
<form method="post" action="{{ path('activite_delete', {'id_activite': activite.idActivite}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activite.idActivite) }}">
    <button class="btn">Supprimer</button>
</form>

templates/activite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/activite/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Modifier Activite{% endblock %}

{% block body %}
    <h1>Modifier Activite</h1>

    {{ include('activite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('activite_index') }}">retour</a>

    {{ include('activite/_delete_form.html.twig') }}
{% endblock %}

templates/activite/index.html.twig
{% extends 'layout.html.twig' %}


{% block body %}

            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table product-overview" id="myTable">
        <thead>
            <tr>
                <th>Id activite</th>
                <th>DescreptionA ctivite</th>
                <th>Prix Activite</th>
                <th>Centre </th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for activite in activites %}
            <tr>
                <td>{{ activite.idActivite }}</td>
                <td>{{ activite.DescreptionActivite }}</td>
                <td>{{ activite.PrixActivite }}</td>
                <td>{{ activite.Centre.nomCentre }}</td>

                <td>
                    <a href="{{ path('activite_show', {'id_activite': activite.idActivite}) }}">show</a>
                    <a href="{{ path('activite_edit', {'id_activite': activite.idActivite}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">non activité trouvez</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('activite_new') }}"> Crée Activite</a>
{% endblock %}

templates/activite/new.html.twig
{% extends 'layout.html.twig' %}


{% block body %}
    <h1>Cree Activite</h1>

    {{ include('activite/_form.html.twig') }}

    <a href="{{ path('activite_index') }}">retour </a>
{% endblock %}

templates/activite/show.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Activite{% endblock %}

{% block body %}
    <h1>Activite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id activite</th>
                <td>{{ activite.idActivite }}</td>
            </tr>
            <tr>
                <th>DescreptionActivite</th>
                <td>{{ activite.DescreptionActivite }}</td>
            </tr>
            <tr>
                <th>PrixActivite</th>
                <td>{{ activite.PrixActivite }}</td>
            </tr>
            <tr>
                <th>Centre</th>
                <td>{{ activite.Centre.nomCentre }}</td>
            </tr>

        </tbody>
    </table>

    <a type = "button" href="{{ path('activite_index') }}">back to list</a>

    <a type = "button" href="{{ path('activite_edit', {'id_activite': activite.idActivite}) }}">Modifier</a>

    {{ include('activite/_delete_form.html.twig') }}
{% endblock %}